# Blog Settings
title: "Nuqtah | نقطة"
description: "النقاط على الحروف"
baseurl: "" # Leave empty if your repo is username.github.io
url: "https://nashatalialii.github.io"

# Theme Setting (We will use a standard one for now)
theme: jekyll-theme-minima

# Localization for Arabic
lang: ar
direction: rtl
